### ISSUE TITLE
Time to release 0.4.0?

### ISSUE THREAD

**Issue by roystgnr** [libantioch/antioch#195]
Antioch 0.3.1 doesn't contain the latest boost.m4 updates, and isn't buildable on my system.  @pbauman has GRINS requiring Antioch 0.4.0, which only exists as master/HEAD at this point, but which has been stable for a while.

**Comment by pbauman** [comment]
I've been waiting because I've gotten very strange behavior with the "kinetics theory" transport in applications, so there are some bugs there. I was hoping we could iron those out before 0.4.0, but master is getting long on the tooth. I think the API is probably stable, with the possible exception of discussion in #146 where one of the functions maybe could change if we update the formulation.

**Comment by pbauman** [comment]
Hmm. Actually, going back and looking at history, the kinetics theory stuff was already in 0.3.0, I just refactored it since then. So maybe that's a bad reason to hold up a release.

**Comment by pbauman** [comment]
0.4.0 has been released.
